apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-native
data:
  application.yml: |
    demo:
      message: Spring Native on Kubernetes!
    server:
      shutdown: graceful
    spring:
      lifecycle:
        timeout-per-shutdown-phase: 15s